# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e637a15ec223960945616adea88355f0d62b90d88e9c9ae235deba1dc0f2f41543017b95b4a02c52a99edaa7974f12a5b528b5adc85412aa01cd7a5768aa61ad

test:
  secret_key_base: 4c49ef9b7c8f29fea6434b0afa8f14a9eb70ec3f446a532a87ec0b7f0f1e0c1fd895d64e520ce2bfa697013b7371b99a492dceefea967bf3cdd8293cac9063a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
